version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sistem-gudang-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=sistem_gudang
      - DB_USERNAME=root
      - DB_PASSWORD=

  db:
    image: mysql:8.0
    container_name: sistem-gudang-db
    environment:
      MYSQL_DATABASE: sistem_gudang
      MYSQL_ROOT_PASSWORD: ''
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

volumes:
  db_data:
